// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLLUBg8x0a3DJ9NJXIrTgAI-tjrYFofyM',
    appId: '1:943086755886:web:f901baf4cab7672be3ffbf',
    messagingSenderId: '943086755886',
    projectId: 'flutterapp-0',
    authDomain: 'flutterapp-0.firebaseapp.com',
    storageBucket: 'flutterapp-0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpJ9DR-XTtgzJcFPfWFZx0ObnIC-QTlk',
    appId: '1:943086755886:ios:2f6bb1c1918b50e3e3ffbf',
    messagingSenderId: '943086755886',
    projectId: 'flutterapp-0',
    storageBucket: 'flutterapp-0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLLUBg8x0a3DJ9NJXIrTgAI-tjrYFofyM',
    appId: '1:943086755886:web:e398396527f50772e3ffbf',
    messagingSenderId: '943086755886',
    projectId: 'flutterapp-0',
    authDomain: 'flutterapp-0.firebaseapp.com',
    storageBucket: 'flutterapp-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpJ9DR-XTtgzJcFPfWFZx0ObnIC-QTlk',
    appId: '1:943086755886:ios:2f6bb1c1918b50e3e3ffbf',
    messagingSenderId: '943086755886',
    projectId: 'flutterapp-0',
    storageBucket: 'flutterapp-0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEYDiHe4axgZWOcdM7yehZLI2AroC-9Q',
    appId: '1:943086755886:android:00dec871b7d163bde3ffbf',
    messagingSenderId: '943086755886',
    projectId: 'flutterapp-0',
    storageBucket: 'flutterapp-0.firebasestorage.app',
  );

}